config/routes.rb
require "resque_web"

Rails.application.routes.draw do

  get 'admin_sections/index'

  get 'admin_sections/list_users'

  get 'admin_sections/edit_user'

  devise_for :users
  

  mount ResqueWeb::Engine => "/resque_web"

  resources :correlations
  resources :correlation_collections
  resources :asset_types
  resources :asset_types

  resources :simulations, except: [:show, :update]
  post 'simulations/run_simulation' => 'simulations#run_simulation'
  
  get 'simulations/manage' => 'simulations#manage'
  get 'simulation' => 'simulations#index'
  get 'simulations/results' => 'simulations#results'
  post 'simulations/results' => 'simulations#results'
  patch 'simulations/results' => 'simulations#results'
  get 'simulations/matrix_test' => 'simulations#matrix_test'
  get 'simulations/sources' => 'simulations#sources'
  get 'simulations/build_simulation' => 'simulations#build_simulation'

  root 'simulations#index'

end

app/models/asset_type.rb
class AssetType < ActiveRecord::Base
	has_many :starting_assets
end

app/models/correlation.rb
class Correlation < ActiveRecord::Base
  belongs_to :correlation_collection
  belongs_to :asset_type1, :class_name => "AssetType"
  belongs_to :asset_type2, :class_name => "AssetType"
end

app/models/correlation_collection.rb
class CorrelationCollection < ActiveRecord::Base
	has_many :correlations
	accepts_nested_attributes_for :correlations, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
end

app/models/path.rb
class Path < ActiveRecord::Base
	belongs_to :simulation
	has_many :path_portfolios, :dependent => :destroy
end

app/models/path_asset.rb
class PathAsset < ActiveRecord::Base
	belongs_to :path_portfolio
	belongs_to :asset_type
end

app/models/path_portfolio.rb
class PathPortfolio < ActiveRecord::Base
	belongs_to :path
	has_many :path_assets, :dependent => :destroy
end

app/models/simulation.rb
class Simulation < ActiveRecord::Base
	belongs_to :correlation_collection
	has_many :starting_assets, :dependent => :destroy
	has_many :target_allocations, :dependent => :destroy
	has_many :paths, :dependent => :destroy
	accepts_nested_attributes_for :starting_assets, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
	accepts_nested_attributes_for :target_allocations, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
		
	validates :title, presence: true
	validates :number_of_paths, inclusion: 1..1000
end

app/models/starting_asset.rb
class StartingAsset < ActiveRecord::Base
	belongs_to :simulation
	belongs_to :asset_type
end

app/models/target_allocation.rb
class TargetAllocation < ActiveRecord::Base
	belongs_to :simulation
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/correlation_collections_controller.rb
class CorrelationCollectionsController < ApplicationController
  before_action :check_admin_access
  before_action :set_correlation_collection, only: [:show, :edit, :update, :destroy]

  # GET /correlation_collections
  # GET /correlation_collections.json
  def index
    @correlation_collections = CorrelationCollection.all
  end

  # GET /correlation_collections/1
  # GET /correlation_collections/1.json
  def show
  end

  # GET /correlation_collections/new
  def new
    @correlation_collection = CorrelationCollection.new
    @asset_types = AssetType.all
  end

  # GET /correlation_collections/1/edit
  def edit
    @asset_types = AssetType.all
  end

  # POST /correlation_collections
  # POST /correlation_collections.json
  def create
    @correlation_collection = CorrelationCollection.new(correlation_collection_params)

    respond_to do |format|
      if @correlation_collection.save
        format.html { redirect_to @correlation_collection, notice: 'Correlation collection was successfully created.' }
        format.json { render :show, status: :created, location: @correlation_collection }
      else
        format.html { render :new }
        format.json { render json: @correlation_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /correlation_collections/1
  # PATCH/PUT /correlation_collections/1.json
  def update
    respond_to do |format|
      if @correlation_collection.update(correlation_collection_params)
        format.html { redirect_to @correlation_collection, notice: 'Correlation collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @correlation_collection }
      else
        format.html { render :edit }
        format.json { render json: @correlation_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /correlation_collections/1
  # DELETE /correlation_collections/1.json
  def destroy
    @correlation_collection.destroy
    respond_to do |format|
      format.html { redirect_to correlation_collections_url, notice: 'Correlation collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_correlation_collection
      @correlation_collection = CorrelationCollection.includes(:correlations).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def correlation_collection_params
      params.require(:correlation_collection).permit(:title,
        {correlations_attributes: [:id, :correlation_amount, :asset_type1_id, :asset_type2_id, :_destroy]})
    end
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
end

app/helpers/admin_sections_helper.rb
module AdminSectionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n","")})
	end
	
end

app/helpers/asset_types_helper.rb
module AssetTypesHelper
end

app/helpers/correlation_collections_helper.rb
module CorrelationCollectionsHelper
end

app/helpers/correlations_helper.rb
module CorrelationsHelper
end

app/helpers/path_assets_helper.rb
module PathAssetsHelper
end

app/helpers/path_portfolios_helper.rb
module PathPortfoliosHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/helpers/starting_assets_helper.rb
module StartingAssetsHelper
end

app/helpers/target_allocations_helper.rb
module TargetAllocationsHelper
end

app/views/correlation_collections/_correlation_fields.html.erb
<fieldset class="fieldset-noborder">
	<div class="field">
		<%= f.hidden_field :id %>
		<%= f.label :correlation_amount, 'Correlation (%)' %>
		<%= f.text_field :correlation_amount %>
		<% options1 = options_from_collection_for_select(@asset_types, 'id', 'name',f.object.asset_type1_id) %>
		<% options2 = options_from_collection_for_select(@asset_types, 'id', 'name',f.object.asset_type2_id) %>
		<%= f.select :asset_type1_id,  options1%>
		<%= f.select :asset_type2_id,  options2%>
		<%= f.hidden_field :_destroy %>
		<%= link_to "Remove", '#', class: "remove_fields" %>
	</div>
</fieldset>

app/views/correlation_collections/_form.html.erb
<%= form_for(@correlation_collection) do |f| %>
  <% if @correlation_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correlation_collection.errors.count, "error") %> prohibited this correlation_collection from being saved:</h2>

      <ul>
      <% @correlation_collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container-form-large">
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="spacer" style="clear: both;"></div>
    <%= field_set_tag 'Correlations' do %>
    <%= f.fields_for :correlations do |builder| %>
      <%= render 'correlation_fields', f: builder %>
    <% end %>
    <%= link_to_add_fields "Add Correlations", f, :correlations %>
  <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>
<div class="spacer" style="clear: both;"></div>
<br>

app/views/correlation_collections/edit.html.erb
<h1>Editing Correlation Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @correlation_collection %> |
<%= link_to 'Back', correlation_collections_path %>

app/views/correlation_collections/index.html.erb
<h1>Listing Correlation Collections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @correlation_collections.each do |correlation_collection| %>
      <tr>
        <td><%= correlation_collection.title %></td>
        <td><%= link_to 'Show', correlation_collection %></td>
        <td><%= link_to 'Edit', edit_correlation_collection_path(correlation_collection) %></td>
        <td><%= link_to 'Destroy', correlation_collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Correlation collection', new_correlation_collection_path %>

app/views/correlation_collections/new.html.erb
<h1>New Correlation Collection</h1>

<%= render 'form' %>

<%= link_to 'Back', correlation_collections_path %>

app/views/correlation_collections/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @correlation_collection.title %>
</p>

<%= link_to 'Edit', edit_correlation_collection_path(@correlation_collection) %> |
<%= link_to 'Back', correlation_collections_path %>