config/routes.rb
require "resque_web"

Rails.application.routes.draw do

  get 'admin_sections/index'

  get 'admin_sections/list_users'

  get 'admin_sections/edit_user'

  devise_for :users
  

  mount ResqueWeb::Engine => "/resque_web"

  resources :correlations
  resources :correlation_collections
  resources :asset_types
  resources :asset_types

  resources :simulations, except: [:show, :update]
  post 'simulations/run_simulation' => 'simulations#run_simulation'
  
  get 'simulations/manage' => 'simulations#manage'
  get 'simulation' => 'simulations#index'
  get 'simulations/results' => 'simulations#results'
  post 'simulations/results' => 'simulations#results'
  patch 'simulations/results' => 'simulations#results'
  get 'simulations/matrix_test' => 'simulations#matrix_test'
  get 'simulations/sources' => 'simulations#sources'
  get 'simulations/build_simulation' => 'simulations#build_simulation'

  root 'simulations#index'

end

app/models/asset_type.rb
class AssetType < ActiveRecord::Base
	has_many :starting_assets
end

app/models/correlation.rb
class Correlation < ActiveRecord::Base
  belongs_to :correlation_collection
  belongs_to :asset_type1, :class_name => "AssetType"
  belongs_to :asset_type2, :class_name => "AssetType"
end

app/models/correlation_collection.rb
class CorrelationCollection < ActiveRecord::Base
	has_many :correlations
	accepts_nested_attributes_for :correlations, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
end

app/models/path.rb
class Path < ActiveRecord::Base
	belongs_to :simulation
	has_many :path_portfolios, :dependent => :destroy
end

app/models/path_asset.rb
class PathAsset < ActiveRecord::Base
	belongs_to :path_portfolio
	belongs_to :asset_type
end

app/models/path_portfolio.rb
class PathPortfolio < ActiveRecord::Base
	belongs_to :path
	has_many :path_assets, :dependent => :destroy
end

app/models/simulation.rb
class Simulation < ActiveRecord::Base
	belongs_to :correlation_collection
	has_many :starting_assets, :dependent => :destroy
	has_many :target_allocations, :dependent => :destroy
	has_many :paths, :dependent => :destroy
	accepts_nested_attributes_for :starting_assets, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
	accepts_nested_attributes_for :target_allocations, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
		
	validates :title, presence: true
	validates :number_of_paths, inclusion: 1..1000
end

app/models/starting_asset.rb
class StartingAsset < ActiveRecord::Base
	belongs_to :simulation
	belongs_to :asset_type
end

app/models/target_allocation.rb
class TargetAllocation < ActiveRecord::Base
	belongs_to :simulation
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, prepend: true

  def check_admin_access
  	authenticate_user!
  	if current_user.admin_flag
		return
	else
		redirect_to root_url , notice: 'Sorry, only admins can access that'
	end
  end
end

app/controllers/correlations_controller.rb
class CorrelationsController < ApplicationController
  before_action :set_correlation, only: [:show, :edit, :update, :destroy]

  # GET /correlations
  # GET /correlations.json
  def index
    @correlations = Correlation.all
  end

  # GET /correlations/1
  # GET /correlations/1.json
  def show
  end

  # GET /correlations/new
  def new
    @correlation = Correlation.new
  end

  # GET /correlations/1/edit
  def edit
  end

  # POST /correlations
  # POST /correlations.json
  def create
    @correlation = Correlation.new(correlation_params)

    respond_to do |format|
      if @correlation.save
        format.html { redirect_to @correlation, notice: 'Correlation was successfully created.' }
        format.json { render :show, status: :created, location: @correlation }
      else
        format.html { render :new }
        format.json { render json: @correlation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /correlations/1
  # PATCH/PUT /correlations/1.json
  def update
    respond_to do |format|
      if @correlation.update(correlation_params)
        format.html { redirect_to @correlation, notice: 'Correlation was successfully updated.' }
        format.json { render :show, status: :ok, location: @correlation }
      else
        format.html { render :edit }
        format.json { render json: @correlation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /correlations/1
  # DELETE /correlations/1.json
  def destroy
    @correlation.destroy
    respond_to do |format|
      format.html { redirect_to correlations_url, notice: 'Correlation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_correlation
      @correlation = Correlation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def correlation_params
      params.require(:correlation).permit(:correlation_collection_id, :asset_type1_id, :asset_type2_id)
    end
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
end

app/helpers/admin_sections_helper.rb
module AdminSectionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n","")})
	end
	
end

app/helpers/asset_types_helper.rb
module AssetTypesHelper
end

app/helpers/correlations_helper.rb
module CorrelationsHelper
end

app/helpers/path_assets_helper.rb
module PathAssetsHelper
end

app/helpers/path_portfolios_helper.rb
module PathPortfoliosHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/helpers/starting_assets_helper.rb
module StartingAssetsHelper
end

app/helpers/target_allocations_helper.rb
module TargetAllocationsHelper
end

app/views/correlations/_form.html.erb
<%= form_for(@correlation) do |f| %>
  <% if @correlation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correlation.errors.count, "error") %> prohibited this correlation from being saved:</h2>

      <ul>
      <% @correlation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :correlation_collection_id %><br>
    <%= f.text_field :correlation_collection_id %>
  </div>
  <div class="field">
    <%= f.label :asset_type1_id %><br>
    <%= f.text_field :asset_type1_id %>
  </div>
  <div class="field">
    <%= f.label :asset_type2_id %><br>
    <%= f.text_field :asset_type2_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/correlations/edit.html.erb
<h1>Editing Correlation</h1>

<%= render 'form' %>

<%= link_to 'Show', @correlation %> |
<%= link_to 'Back', correlations_path %>

app/views/correlations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Correlations</h1>

<table>
  <thead>
    <tr>
      <th>Correlation collection</th>
      <th>Asset type1</th>
      <th>Asset type2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @correlations.each do |correlation| %>
      <tr>
        <td><%= correlation.correlation_collection %></td>
        <td><%= correlation.asset_type1 %></td>
        <td><%= correlation.asset_type2 %></td>
        <td><%= link_to 'Show', correlation %></td>
        <td><%= link_to 'Edit', edit_correlation_path(correlation) %></td>
        <td><%= link_to 'Destroy', correlation, method: :delete , data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Correlation', new_correlation_path %>

app/views/correlations/new.html.erb
<h1>New Correlation</h1>

<%= render 'form' %>

<%= link_to 'Back', correlations_path %>

app/views/correlations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Correlation collection:</strong>
  <%= @correlation.correlation_collection %>
</p>

<p>
  <strong>Asset type1:</strong>
  <%= @correlation.asset_type1 %>
</p>

<p>
  <strong>Asset type2:</strong>
  <%= @correlation.asset_type2 %>
</p>

<%= link_to 'Edit', edit_correlation_path(@correlation) %> |
<%= link_to 'Back', correlations_path %>