config/routes.rb
require "resque_web"

Rails.application.routes.draw do

  get 'admin_sections/index'

  get 'admin_sections/list_users'

  get 'admin_sections/edit_user'

  devise_for :users
  

  mount ResqueWeb::Engine => "/resque_web"

  resources :correlations
  resources :correlation_collections
  resources :asset_types
  resources :asset_types

  resources :simulations, except: [:show, :update]
  post 'simulations/run_simulation' => 'simulations#run_simulation'
  
  get 'simulations/manage' => 'simulations#manage'
  get 'simulation' => 'simulations#index'
  get 'simulations/results' => 'simulations#results'
  post 'simulations/results' => 'simulations#results'
  patch 'simulations/results' => 'simulations#results'
  get 'simulations/matrix_test' => 'simulations#matrix_test'
  get 'simulations/sources' => 'simulations#sources'
  get 'simulations/build_simulation' => 'simulations#build_simulation'

  root 'simulations#index'

end

app/models/asset_type.rb
class AssetType < ActiveRecord::Base
	has_many :starting_assets
end

app/models/correlation.rb
class Correlation < ActiveRecord::Base
  belongs_to :correlation_collection
  belongs_to :asset_type1, :class_name => "AssetType"
  belongs_to :asset_type2, :class_name => "AssetType"
end

app/models/correlation_collection.rb
class CorrelationCollection < ActiveRecord::Base
	has_many :correlations
	accepts_nested_attributes_for :correlations, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
end

app/models/path.rb
class Path < ActiveRecord::Base
	belongs_to :simulation
	has_many :path_portfolios, :dependent => :destroy
end

app/models/path_asset.rb
class PathAsset < ActiveRecord::Base
	belongs_to :path_portfolio
	belongs_to :asset_type
end

app/models/path_portfolio.rb
class PathPortfolio < ActiveRecord::Base
	belongs_to :path
	has_many :path_assets, :dependent => :destroy
end

app/models/simulation.rb
class Simulation < ActiveRecord::Base
	belongs_to :correlation_collection
	has_many :starting_assets, :dependent => :destroy
	has_many :target_allocations, :dependent => :destroy
	has_many :paths, :dependent => :destroy
	accepts_nested_attributes_for :starting_assets, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
	accepts_nested_attributes_for :target_allocations, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
		
	validates :title, presence: true
	validates :number_of_paths, inclusion: 1..1000
end

app/models/starting_asset.rb
class StartingAsset < ActiveRecord::Base
	belongs_to :simulation
	belongs_to :asset_type
end

app/models/target_allocation.rb
class TargetAllocation < ActiveRecord::Base
	belongs_to :simulation
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/asset_types_controller.rb
class AssetTypesController < ApplicationController
  before_action :check_admin_access
  before_action :set_asset_type, only: [:show, :edit, :update, :destroy]

  # GET /asset_types
  # GET /asset_types.json
  def index
    @asset_types = AssetType.all
  end

  # GET /asset_types/1
  # GET /asset_types/1.json
  def show
  end

  # GET /asset_types/new
  def new
    @asset_type = AssetType.new
  end

  # GET /asset_types/1/edit
  def edit
  end

  # POST /asset_types
  # POST /asset_types.json
  def create
    @asset_type = AssetType.new(asset_type_params)

    respond_to do |format|
      if @asset_type.save
        format.html { redirect_to @asset_type, notice: 'Asset type was successfully created.' }
        format.json { render :show, status: :created, location: @asset_type }
      else
        format.html { render :new }
        format.json { render json: @asset_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asset_types/1
  # PATCH/PUT /asset_types/1.json
  def update
    respond_to do |format|
      if @asset_type.update(asset_type_params)
        format.html { redirect_to @asset_type, notice: 'Asset type was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset_type }
      else
        format.html { render :edit }
        format.json { render json: @asset_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asset_types/1
  # DELETE /asset_types/1.json
  def destroy
    @asset_type.destroy
    respond_to do |format|
      format.html { redirect_to asset_types_url, notice: 'Asset type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset_type
      @asset_type = AssetType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_type_params
      params.require(:asset_type).permit(:name, :historical_std_deviation, :historical_average_return)
    end
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
end

app/helpers/admin_sections_helper.rb
module AdminSectionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n","")})
	end
	
end

app/helpers/asset_types_helper.rb
module AssetTypesHelper
end

app/helpers/correlations_helper.rb
module CorrelationsHelper
end

app/helpers/path_assets_helper.rb
module PathAssetsHelper
end

app/helpers/path_portfolios_helper.rb
module PathPortfoliosHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/helpers/starting_assets_helper.rb
module StartingAssetsHelper
end

app/helpers/target_allocations_helper.rb
module TargetAllocationsHelper
end

app/views/asset_types/_form.html.erb
<%= form_for(@asset_type) do |f| %>
  <% if @asset_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset_type.errors.count, "error") %> prohibited this asset_type from being saved:</h2>

      <ul>
      <% @asset_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container-form-medium">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :historical_std_deviation %>
      <%= f.text_field :historical_std_deviation %>
    </div>
    <div class="field">
      <%= f.label :historical_average_return %>
      <%= f.text_field :historical_average_return %>
    </div>
    <div class="spacer" style="clear: both;"></div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>
<div class="spacer" style="clear: both;"></div>
<br>

app/views/asset_types/edit.html.erb
	<h3>Editing Asset Type</h3>

	<%= render 'form' %>

	<%= link_to 'Show', @asset_type %> |
	<%= link_to 'Back', asset_types_path %>

app/views/asset_types/index.html.erb
  <h3>Listing Asset Types</h3>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Historical std deviation</th>
        <th>Historical average return</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @asset_types.each do |asset_type| %>
        <tr>
          <td><%= asset_type.name %></td>
          <td><%= asset_type.historical_std_deviation %></td>
          <td><%= asset_type.historical_average_return %></td>
          <td><%= link_to 'Show', asset_type %></td>
          <td><%= link_to 'Edit', edit_asset_type_path(asset_type) %></td>
          <td><%= link_to 'Destroy', asset_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Asset type', new_asset_type_path %>
  <div class="cleaner"></div>

app/views/asset_types/new.html.erb
<h1>New Asset Type</h1>

<%= render 'form' %>

<%= link_to 'Back', asset_types_path %>

app/views/asset_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @asset_type.name %>
</p>

<p>
  <strong>Historical std deviation:</strong>
  <%= @asset_type.historical_std_deviation %>
</p>

<p>
  <strong>Historical average return:</strong>
  <%= @asset_type.historical_average_return %>
</p>

<%= link_to 'Edit', edit_asset_type_path(@asset_type) %> |
<%= link_to 'Back', asset_types_path %>