config/routes.rb
require "resque_web"

Rails.application.routes.draw do

  get 'admin_sections/index'

  get 'admin_sections/list_users'

  get 'admin_sections/edit_user'

  devise_for :users
  

  mount ResqueWeb::Engine => "/resque_web"

  resources :correlations
  resources :correlation_collections
  resources :asset_types
  resources :asset_types

  resources :simulations, except: [:show, :update]
  post 'simulations/run_simulation' => 'simulations#run_simulation'
  
  get 'simulations/manage' => 'simulations#manage'
  get 'simulation' => 'simulations#index'
  get 'simulations/results' => 'simulations#results'
  post 'simulations/results' => 'simulations#results'
  patch 'simulations/results' => 'simulations#results'
  get 'simulations/matrix_test' => 'simulations#matrix_test'
  get 'simulations/sources' => 'simulations#sources'
  get 'simulations/build_simulation' => 'simulations#build_simulation'

  root 'simulations#index'

end

app/models/asset_type.rb
class AssetType < ActiveRecord::Base
	has_many :starting_assets
end

app/models/correlation.rb
class Correlation < ActiveRecord::Base
  belongs_to :correlation_collection
  belongs_to :asset_type1, :class_name => "AssetType"
  belongs_to :asset_type2, :class_name => "AssetType"
end

app/models/correlation_collection.rb
class CorrelationCollection < ActiveRecord::Base
	has_many :correlations
	accepts_nested_attributes_for :correlations, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
end

app/models/path.rb
class Path < ActiveRecord::Base
	belongs_to :simulation
	has_many :path_portfolios, :dependent => :destroy
end

app/models/path_asset.rb
class PathAsset < ActiveRecord::Base
	belongs_to :path_portfolio
	belongs_to :asset_type
end

app/models/path_portfolio.rb
class PathPortfolio < ActiveRecord::Base
	belongs_to :path
	has_many :path_assets, :dependent => :destroy
end

app/models/simulation.rb
class Simulation < ActiveRecord::Base
	belongs_to :correlation_collection
	has_many :starting_assets, :dependent => :destroy
	has_many :target_allocations, :dependent => :destroy
	has_many :paths, :dependent => :destroy
	accepts_nested_attributes_for :starting_assets, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
	accepts_nested_attributes_for :target_allocations, :allow_destroy => true, 
		:reject_if => proc { |attributes| attributes['_destroy'] == '1' }
		
	validates :title, presence: true
	validates :number_of_paths, inclusion: 1..1000
end

app/models/starting_asset.rb
class StartingAsset < ActiveRecord::Base
	belongs_to :simulation
	belongs_to :asset_type
end

app/models/target_allocation.rb
class TargetAllocation < ActiveRecord::Base
	belongs_to :simulation
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
end

app/helpers/admin_sections_helper.rb
module AdminSectionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_fields", f: builder)
		end
		link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n","")})
	end
	
end

app/helpers/asset_types_helper.rb
module AssetTypesHelper
end

app/helpers/correlations_helper.rb
module CorrelationsHelper
end

app/helpers/path_assets_helper.rb
module PathAssetsHelper
end

app/helpers/path_portfolios_helper.rb
module PathPortfoliosHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/simulations_helper.rb
module SimulationsHelper
end

app/helpers/starting_assets_helper.rb
module StartingAssetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>

  
	</head>

	
</head>
<body>
	<div class="container">
		<div class="header">
			
			<div class="header-img">
				<%= image_tag("Money.png") %>
			</div>
			<h1 class="header-heading">FU Money</h1>
		</div>
		<div class="nav-bar">
			<ul class="nav">
				<li><%= link_to 'New Sim', simulations_build_simulation_path %></li>
                <li><%= link_to 'View Results', simulations_results_path %></li>
                <li><%= link_to 'Manage Sims', simulations_manage_path %></li>
	            <% if user_signed_in? %>
	                <% if current_user.admin_flag %>
		                <li><%= link_to 'Asset Types', asset_types_path %></li>
		                <li><%= link_to 'Corr Collection', correlation_collections_path %></li>
	                <% end %>
	               <% end %>
                <li><%= link_to 'External Sources', simulations_sources_path %></li>
                <li><%= link_to 'Matrix Test', simulations_matrix_test_path %></li>
                <% if user_signed_in? %>
                	<li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
                <% else %>
                	<li><%= link_to 'Sign Up', new_user_registration_path %></li>
                	<li><%= link_to 'Log In', new_user_session_path %></li>
                <% end %>
			</ul>
		</div>
		<div class="content">
			<div class="main">
 	 			<p id="notice"><%= notice %></p>
 	 			<p class="alert"><%= alert %></p>

<%= yield %>

            </div>
        </div>
        <div class="footer">
	    	&copy; 2016 Michael Swofford
	    </div>
    </div>

           

</body>
</html>